// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-UBLKNJO
// DateTime: 6/13/2021 15:54:25
// UserName: tourist
// Input file <.\kompilator.y - 6/13/2021 15:54:19>

// options: conflicts no-lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using Compiler.AST;

namespace Compiler
{
public enum Tokens {error=2,EOF=3,Program=4,Eof=5,Return=6,
    If=7,Else=8,While=9,Read=10,Write=11,IntKeyword=12,
    DoubleKeyword=13,BoolKeyword=14,IntHex=15,True=16,False=17,Assign=18,
    Plus=19,Minus=20,Multiplies=21,Divides=22,Or=23,And=24,
    Not=25,BitOr=26,BitAnd=27,BitNot=28,Equal=29,NotEqual=30,
    Greater=31,GreaterOrEqual=32,Less=33,LessOrEqual=34,OpenRound=35,CloseRound=36,
    OpenCurly=37,CloseCurly=38,Comma=39,SemiColon=40,Ident=41,IntNumber=42,
    IntNumberHex=43,DoubleNumber=44,Literal=45,Error=46};

public struct ValueType
{
    public string val;
    public SyntaxTree node;
    public List<SyntaxTree> node_s;
    public List<string> name_s;
}
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[76];
  private static State[] states = new State[133];
  private static string[] nonTerms = new string[] {
      "block", "body", "inst_block", "inst_s", "read", "write", "return", "declar", 
      "type", "exp", "logic", "relat", "addit", "multip", "bit", "unary", "factor", 
      "statement", "open_statement", "closed_statement", "simple_statement", 
      "name_s", "start", "$accept", "error_eof", };

  static Parser() {
    states[0] = new State(new int[]{4,3,2,130},new int[]{-23,1,-25,132});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{37,7,2,130},new int[]{-1,4,-25,6});
    states[4] = new State(new int[]{5,5});
    states[5] = new State(-2);
    states[6] = new State(-3);
    states[7] = new State(new int[]{38,127,12,18,13,19,14,20,15,21,7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-2,8,-8,128,-9,12,-18,129,-19,22,-20,44,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[8] = new State(new int[]{38,9,12,18,13,19,14,20,15,21,7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-8,10,-18,11,-9,12,-19,22,-20,44,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[9] = new State(-5);
    states[10] = new State(-7);
    states[11] = new State(-8);
    states[12] = new State(new int[]{41,17},new int[]{-22,13});
    states[13] = new State(new int[]{40,14,39,15});
    states[14] = new State(-11);
    states[15] = new State(new int[]{41,16});
    states[16] = new State(-16);
    states[17] = new State(-17);
    states[18] = new State(-12);
    states[19] = new State(-13);
    states[20] = new State(-14);
    states[21] = new State(-15);
    states[22] = new State(-27);
    states[23] = new State(new int[]{35,24});
    states[24] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-10,25,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[25] = new State(new int[]{36,26});
    states[26] = new State(new int[]{7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-18,27,-20,28,-19,22,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[27] = new State(-29);
    states[28] = new State(new int[]{8,29,38,-28,12,-28,13,-28,14,-28,15,-28,7,-28,9,-28,37,-28,6,-28,10,-28,11,-28,20,-28,19,-28,28,-28,25,-28,35,-28,41,-28,42,-28,44,-28,16,-28,17,-28});
    states[29] = new State(new int[]{7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-19,30,-20,31,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[30] = new State(-30);
    states[31] = new State(-33);
    states[32] = new State(new int[]{35,33});
    states[33] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-10,34,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[34] = new State(new int[]{36,35});
    states[35] = new State(new int[]{7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-19,36,-20,37,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[36] = new State(-31);
    states[37] = new State(-34);
    states[38] = new State(-32);
    states[39] = new State(-18);
    states[40] = new State(new int[]{38,125,7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-4,41,-18,126,-19,22,-20,44,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[41] = new State(new int[]{38,42,7,23,9,32,37,40,6,46,10,49,11,56,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-18,43,-19,22,-20,44,-21,38,-3,39,-7,45,-5,48,-6,55,-10,123,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[42] = new State(-25);
    states[43] = new State(-23);
    states[44] = new State(-28);
    states[45] = new State(-19);
    states[46] = new State(new int[]{40,47});
    states[47] = new State(-40);
    states[48] = new State(-20);
    states[49] = new State(new int[]{41,50});
    states[50] = new State(new int[]{40,51,39,52});
    states[51] = new State(-35);
    states[52] = new State(new int[]{15,53});
    states[53] = new State(new int[]{40,54});
    states[54] = new State(-36);
    states[55] = new State(-21);
    states[56] = new State(new int[]{45,62,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-10,57,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[57] = new State(new int[]{40,58,39,59});
    states[58] = new State(-37);
    states[59] = new State(new int[]{15,60});
    states[60] = new State(new int[]{40,61});
    states[61] = new State(-38);
    states[62] = new State(new int[]{40,63});
    states[63] = new State(-39);
    states[64] = new State(new int[]{18,65,23,119,24,121,40,-42,36,-42,39,-42});
    states[65] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-10,66,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[66] = new State(-41);
    states[67] = new State(new int[]{29,68,30,109,31,111,32,113,33,115,34,117,18,-45,23,-45,24,-45,40,-45,36,-45,39,-45});
    states[68] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,69,-14,108,-15,107,-16,106,-17,88});
    states[69] = new State(new int[]{19,70,20,100,29,-46,30,-46,31,-46,32,-46,33,-46,34,-46,18,-46,23,-46,24,-46,40,-46,36,-46,39,-46});
    states[70] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-14,71,-15,107,-16,106,-17,88});
    states[71] = new State(new int[]{21,72,22,102,19,-53,20,-53,29,-53,30,-53,31,-53,32,-53,33,-53,34,-53,18,-53,23,-53,24,-53,40,-53,36,-53,39,-53});
    states[72] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-15,73,-16,106,-17,88});
    states[73] = new State(new int[]{26,74,27,104,21,-56,22,-56,19,-56,20,-56,29,-56,30,-56,31,-56,32,-56,33,-56,34,-56,18,-56,23,-56,24,-56,40,-56,36,-56,39,-56});
    states[74] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,75,-17,88});
    states[75] = new State(-59);
    states[76] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,77,-17,88});
    states[77] = new State(-62);
    states[78] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,79,-17,88});
    states[79] = new State(-63);
    states[80] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,81,-17,88});
    states[81] = new State(-64);
    states[82] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,83,-17,88});
    states[83] = new State(-65);
    states[84] = new State(new int[]{12,85,13,94,20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-10,97,-11,64,-12,67,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[85] = new State(new int[]{36,86});
    states[86] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,87,-17,88});
    states[87] = new State(-66);
    states[88] = new State(-68);
    states[89] = new State(-70);
    states[90] = new State(-71);
    states[91] = new State(-72);
    states[92] = new State(-73);
    states[93] = new State(-74);
    states[94] = new State(new int[]{36,95});
    states[95] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,96,-17,88});
    states[96] = new State(-67);
    states[97] = new State(new int[]{36,98});
    states[98] = new State(-69);
    states[99] = new State(new int[]{19,70,20,100,29,-52,30,-52,31,-52,32,-52,33,-52,34,-52,18,-52,23,-52,24,-52,40,-52,36,-52,39,-52});
    states[100] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-14,101,-15,107,-16,106,-17,88});
    states[101] = new State(new int[]{21,72,22,102,19,-54,20,-54,29,-54,30,-54,31,-54,32,-54,33,-54,34,-54,18,-54,23,-54,24,-54,40,-54,36,-54,39,-54});
    states[102] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-15,103,-16,106,-17,88});
    states[103] = new State(new int[]{26,74,27,104,21,-57,22,-57,19,-57,20,-57,29,-57,30,-57,31,-57,32,-57,33,-57,34,-57,18,-57,23,-57,24,-57,40,-57,36,-57,39,-57});
    states[104] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-16,105,-17,88});
    states[105] = new State(-60);
    states[106] = new State(-61);
    states[107] = new State(new int[]{26,74,27,104,21,-58,22,-58,19,-58,20,-58,29,-58,30,-58,31,-58,32,-58,33,-58,34,-58,18,-58,23,-58,24,-58,40,-58,36,-58,39,-58});
    states[108] = new State(new int[]{21,72,22,102,19,-55,20,-55,29,-55,30,-55,31,-55,32,-55,33,-55,34,-55,18,-55,23,-55,24,-55,40,-55,36,-55,39,-55});
    states[109] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,110,-14,108,-15,107,-16,106,-17,88});
    states[110] = new State(new int[]{19,70,20,100,29,-47,30,-47,31,-47,32,-47,33,-47,34,-47,18,-47,23,-47,24,-47,40,-47,36,-47,39,-47});
    states[111] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,112,-14,108,-15,107,-16,106,-17,88});
    states[112] = new State(new int[]{19,70,20,100,29,-48,30,-48,31,-48,32,-48,33,-48,34,-48,18,-48,23,-48,24,-48,40,-48,36,-48,39,-48});
    states[113] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,114,-14,108,-15,107,-16,106,-17,88});
    states[114] = new State(new int[]{19,70,20,100,29,-49,30,-49,31,-49,32,-49,33,-49,34,-49,18,-49,23,-49,24,-49,40,-49,36,-49,39,-49});
    states[115] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,116,-14,108,-15,107,-16,106,-17,88});
    states[116] = new State(new int[]{19,70,20,100,29,-50,30,-50,31,-50,32,-50,33,-50,34,-50,18,-50,23,-50,24,-50,40,-50,36,-50,39,-50});
    states[117] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-13,118,-14,108,-15,107,-16,106,-17,88});
    states[118] = new State(new int[]{19,70,20,100,29,-51,30,-51,31,-51,32,-51,33,-51,34,-51,18,-51,23,-51,24,-51,40,-51,36,-51,39,-51});
    states[119] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-12,120,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[120] = new State(new int[]{29,68,30,109,31,111,32,113,33,115,34,117,18,-43,23,-43,24,-43,40,-43,36,-43,39,-43});
    states[121] = new State(new int[]{20,76,19,78,28,80,25,82,35,84,41,89,42,90,44,91,16,92,17,93},new int[]{-12,122,-13,99,-14,108,-15,107,-16,106,-17,88});
    states[122] = new State(new int[]{29,68,30,109,31,111,32,113,33,115,34,117,18,-44,23,-44,24,-44,40,-44,36,-44,39,-44});
    states[123] = new State(new int[]{40,124});
    states[124] = new State(-22);
    states[125] = new State(-26);
    states[126] = new State(-24);
    states[127] = new State(-6);
    states[128] = new State(-9);
    states[129] = new State(-10);
    states[130] = new State(new int[]{5,131});
    states[131] = new State(-75);
    states[132] = new State(-4);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-24, new int[]{-23,3});
    rules[2] = new Rule(-23, new int[]{4,-1,5});
    rules[3] = new Rule(-23, new int[]{4,-25});
    rules[4] = new Rule(-23, new int[]{-25});
    rules[5] = new Rule(-1, new int[]{37,-2,38});
    rules[6] = new Rule(-1, new int[]{37,38});
    rules[7] = new Rule(-2, new int[]{-2,-8});
    rules[8] = new Rule(-2, new int[]{-2,-18});
    rules[9] = new Rule(-2, new int[]{-8});
    rules[10] = new Rule(-2, new int[]{-18});
    rules[11] = new Rule(-8, new int[]{-9,-22,40});
    rules[12] = new Rule(-9, new int[]{12});
    rules[13] = new Rule(-9, new int[]{13});
    rules[14] = new Rule(-9, new int[]{14});
    rules[15] = new Rule(-9, new int[]{15});
    rules[16] = new Rule(-22, new int[]{-22,39,41});
    rules[17] = new Rule(-22, new int[]{41});
    rules[18] = new Rule(-21, new int[]{-3});
    rules[19] = new Rule(-21, new int[]{-7});
    rules[20] = new Rule(-21, new int[]{-5});
    rules[21] = new Rule(-21, new int[]{-6});
    rules[22] = new Rule(-21, new int[]{-10,40});
    rules[23] = new Rule(-4, new int[]{-4,-18});
    rules[24] = new Rule(-4, new int[]{-18});
    rules[25] = new Rule(-3, new int[]{37,-4,38});
    rules[26] = new Rule(-3, new int[]{37,38});
    rules[27] = new Rule(-18, new int[]{-19});
    rules[28] = new Rule(-18, new int[]{-20});
    rules[29] = new Rule(-19, new int[]{7,35,-10,36,-18});
    rules[30] = new Rule(-19, new int[]{7,35,-10,36,-20,8,-19});
    rules[31] = new Rule(-19, new int[]{9,35,-10,36,-19});
    rules[32] = new Rule(-20, new int[]{-21});
    rules[33] = new Rule(-20, new int[]{7,35,-10,36,-20,8,-20});
    rules[34] = new Rule(-20, new int[]{9,35,-10,36,-20});
    rules[35] = new Rule(-5, new int[]{10,41,40});
    rules[36] = new Rule(-5, new int[]{10,41,39,15,40});
    rules[37] = new Rule(-6, new int[]{11,-10,40});
    rules[38] = new Rule(-6, new int[]{11,-10,39,15,40});
    rules[39] = new Rule(-6, new int[]{11,45,40});
    rules[40] = new Rule(-7, new int[]{6,40});
    rules[41] = new Rule(-10, new int[]{-11,18,-10});
    rules[42] = new Rule(-10, new int[]{-11});
    rules[43] = new Rule(-11, new int[]{-11,23,-12});
    rules[44] = new Rule(-11, new int[]{-11,24,-12});
    rules[45] = new Rule(-11, new int[]{-12});
    rules[46] = new Rule(-12, new int[]{-12,29,-13});
    rules[47] = new Rule(-12, new int[]{-12,30,-13});
    rules[48] = new Rule(-12, new int[]{-12,31,-13});
    rules[49] = new Rule(-12, new int[]{-12,32,-13});
    rules[50] = new Rule(-12, new int[]{-12,33,-13});
    rules[51] = new Rule(-12, new int[]{-12,34,-13});
    rules[52] = new Rule(-12, new int[]{-13});
    rules[53] = new Rule(-13, new int[]{-13,19,-14});
    rules[54] = new Rule(-13, new int[]{-13,20,-14});
    rules[55] = new Rule(-13, new int[]{-14});
    rules[56] = new Rule(-14, new int[]{-14,21,-15});
    rules[57] = new Rule(-14, new int[]{-14,22,-15});
    rules[58] = new Rule(-14, new int[]{-15});
    rules[59] = new Rule(-15, new int[]{-15,26,-16});
    rules[60] = new Rule(-15, new int[]{-15,27,-16});
    rules[61] = new Rule(-15, new int[]{-16});
    rules[62] = new Rule(-16, new int[]{20,-16});
    rules[63] = new Rule(-16, new int[]{19,-16});
    rules[64] = new Rule(-16, new int[]{28,-16});
    rules[65] = new Rule(-16, new int[]{25,-16});
    rules[66] = new Rule(-16, new int[]{35,12,36,-16});
    rules[67] = new Rule(-16, new int[]{35,13,36,-16});
    rules[68] = new Rule(-16, new int[]{-17});
    rules[69] = new Rule(-17, new int[]{35,-10,36});
    rules[70] = new Rule(-17, new int[]{41});
    rules[71] = new Rule(-17, new int[]{42});
    rules[72] = new Rule(-17, new int[]{44});
    rules[73] = new Rule(-17, new int[]{16});
    rules[74] = new Rule(-17, new int[]{17});
    rules[75] = new Rule(-25, new int[]{2,5});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> Program, block, Eof
{
            Console.WriteLine("Here is a program!");
            YYAccept();
        }
        break;
      case 3: // start -> Program, error_eof
{   
            PrintSyntaxError("Syntax error in line", LocationStack[LocationStack.Depth-1].StartLine);
            Console.WriteLine("AAAAA");
            YYAbort();
        }
        break;
      case 4: // start -> error_eof
{
            PrintSyntaxError("The starting word is missing");
            Console.WriteLine("BBBBBB");
            YYAbort();
        }
        break;
      case 5: // block -> OpenCurly, body, CloseCurly
{
            CurrentSemanticValue.node_s = ValueStack[ValueStack.Depth-2].node_s;
            Compiler.code = ValueStack[ValueStack.Depth-2].node_s;
            foreach (var x in CurrentSemanticValue.node_s) {
                Print(x);
            }
        }
        break;
      case 6: // block -> OpenCurly, CloseCurly
{}
        break;
      case 7: // body -> body, declar
{ 
            foreach (var x in ValueStack[ValueStack.Depth-1].node_s) {
                ValueStack[ValueStack.Depth-2].node_s.Add(x);
            }
            CurrentSemanticValue.node_s = ValueStack[ValueStack.Depth-2].node_s;
        }
        break;
      case 8: // body -> body, statement
{
            ValueStack[ValueStack.Depth-2].node_s.Add(ValueStack[ValueStack.Depth-1].node);
            CurrentSemanticValue.node_s = ValueStack[ValueStack.Depth-2].node_s;
        }
        break;
      case 9: // body -> declar
{
            CurrentSemanticValue.node_s = ValueStack[ValueStack.Depth-1].node_s;
        }
        break;
      case 10: // body -> statement
{
            CurrentSemanticValue.node_s = new List<SyntaxTree>();
            CurrentSemanticValue.node_s.Add(ValueStack[ValueStack.Depth-1].node);
        }
        break;
      case 11: // declar -> type, name_s, SemiColon
{
            CurrentSemanticValue.node_s = new List<SyntaxTree>();
            var node = ValueStack[ValueStack.Depth-2].name_s;
            foreach (var x in node) {
                CurrentSemanticValue.node_s.Add(new Declar(ValueStack[ValueStack.Depth-3].val, x));
                Compiler.table.Add(x, ValueStack[ValueStack.Depth-3].val);
            }
        }
        break;
      case 16: // name_s -> name_s, Comma, Ident
{
            ValueStack[ValueStack.Depth-3].name_s.Add(ValueStack[ValueStack.Depth-1].val);
            CurrentSemanticValue.name_s = ValueStack[ValueStack.Depth-3].name_s;
        }
        break;
      case 17: // name_s -> Ident
{
            CurrentSemanticValue.name_s = new List<string>();
            CurrentSemanticValue.name_s.Add(ValueStack[ValueStack.Depth-1].val);
        }
        break;
      case 23: // inst_s -> inst_s, statement
{
            ValueStack[ValueStack.Depth-2].node_s.Add(ValueStack[ValueStack.Depth-1].node);
            CurrentSemanticValue.node_s = ValueStack[ValueStack.Depth-2].node_s;
        }
        break;
      case 24: // inst_s -> statement
{
            CurrentSemanticValue.node_s = new List<SyntaxTree>();
            CurrentSemanticValue.node_s.Add(ValueStack[ValueStack.Depth-1].node);
        }
        break;
      case 25: // inst_block -> OpenCurly, inst_s, CloseCurly
{
            CurrentSemanticValue.node = new Statement(ValueStack[ValueStack.Depth-2].node_s);
        }
        break;
      case 26: // inst_block -> OpenCurly, CloseCurly
{
            CurrentSemanticValue.node = new Statement();
        }
        break;
      case 27: // statement -> open_statement
{  
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 28: // statement -> closed_statement
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 29: // open_statement -> If, OpenRound, exp, CloseRound, statement
{
            CurrentSemanticValue.node = new IfOnly(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node);
        }
        break;
      case 30: // open_statement -> If, OpenRound, exp, CloseRound, closed_statement, Else, 
               //                   open_statement
{
            CurrentSemanticValue.node = new IfElse(ValueStack[ValueStack.Depth-5].node, ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node);
        }
        break;
      case 31: // open_statement -> While, OpenRound, exp, CloseRound, open_statement
{
            var node = new While(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, "While_op");
            CurrentSemanticValue.node = node;
        }
        break;
      case 32: // closed_statement -> simple_statement
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 33: // closed_statement -> If, OpenRound, exp, CloseRound, closed_statement, Else, 
               //                     closed_statement
{
            CurrentSemanticValue.node = new IfElse(ValueStack[ValueStack.Depth-5].node, ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node);
        }
        break;
      case 34: // closed_statement -> While, OpenRound, exp, CloseRound, closed_statement
{
            var node = new While(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, "While_cl");
            CurrentSemanticValue.node = node;
        }
        break;
      case 35: // read -> Read, Ident, SemiColon
{
            CurrentSemanticValue.node = new Read(ValueStack[ValueStack.Depth-2].val, ReadType.Decimal, LocationStack[LocationStack.Depth-3].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 36: // read -> Read, Ident, Comma, IntHex, SemiColon
{
            CurrentSemanticValue.node = new Read(ValueStack[ValueStack.Depth-4].val, ReadType.Hexadecimal, LocationStack[LocationStack.Depth-5].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 37: // write -> Write, exp, SemiColon
{
            CurrentSemanticValue.node = new Write(ValueStack[ValueStack.Depth-2].node, WriteType.Decimal, LocationStack[LocationStack.Depth-3].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 38: // write -> Write, exp, Comma, IntHex, SemiColon
{
            CurrentSemanticValue.node = new Write(ValueStack[ValueStack.Depth-4].node, WriteType.Hexadecimal, LocationStack[LocationStack.Depth-5].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 39: // write -> Write, Literal, SemiColon
{
            CurrentSemanticValue.node = new Write(ValueStack[ValueStack.Depth-2].val, LocationStack[LocationStack.Depth-3].StartLine);
            CurrentSemanticValue.node.CheckType();
            string tt = Compiler.NewTemp();
            tt = "@" + tt.Substring(1);
            Compiler.literal.Add(ValueStack[ValueStack.Depth-2].val, tt);
        }
        break;
      case 40: // return -> Return, SemiColon
{
            CurrentSemanticValue.node = new Return(LocationStack[LocationStack.Depth-2].StartLine);
        }
        break;
      case 41: // exp -> logic, Assign, exp
{
            CurrentSemanticValue.node = new AssignOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 42: // exp -> logic
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 43: // logic -> logic, Or, relat
{
            CurrentSemanticValue.node = new LogicalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, LogicalType.Or, LocationStack[LocationStack.Depth-2].StartLine);
        }
        break;
      case 44: // logic -> logic, And, relat
{
            CurrentSemanticValue.node = new LogicalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, LogicalType.And, LocationStack[LocationStack.Depth-2].StartLine);
        }
        break;
      case 45: // logic -> relat
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 46: // relat -> relat, Equal, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.Equal, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 47: // relat -> relat, NotEqual, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.NotEqual, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 48: // relat -> relat, Greater, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.Greater, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 49: // relat -> relat, GreaterOrEqual, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.GreaterOrEqual, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 50: // relat -> relat, Less, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.Less, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 51: // relat -> relat, LessOrEqual, addit
{
            CurrentSemanticValue.node = new RelationalOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, RelationalType.LessOrEqual, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 52: // relat -> addit
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 53: // addit -> addit, Plus, multip
{
            CurrentSemanticValue.node = new ArithOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, ArithType.Addition, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 54: // addit -> addit, Minus, multip
{
            CurrentSemanticValue.node = new ArithOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, ArithType.Substraction, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 55: // addit -> multip
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 56: // multip -> multip, Multiplies, bit
{
            CurrentSemanticValue.node = new ArithOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, ArithType.Multiplication, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 57: // multip -> multip, Divides, bit
{
            CurrentSemanticValue.node = new ArithOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, ArithType.Division, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 58: // multip -> bit
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 59: // bit -> bit, BitOr, unary
{
            CurrentSemanticValue.node = new BitOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, BitType.Or, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 60: // bit -> bit, BitAnd, unary
{
            CurrentSemanticValue.node = new BitOperator(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, BitType.And, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 61: // bit -> unary
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 62: // unary -> Minus, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.Minus, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 63: // unary -> Plus, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.Plus, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 64: // unary -> BitNot, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.BitNot, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 65: // unary -> Not, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.Not, LocationStack[LocationStack.Depth-2].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 66: // unary -> OpenRound, IntKeyword, CloseRound, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.ToInt, LocationStack[LocationStack.Depth-3].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 67: // unary -> OpenRound, DoubleKeyword, CloseRound, unary
{
            CurrentSemanticValue.node = new UnaryOperator(ValueStack[ValueStack.Depth-1].node, UnaryType.ToDouble, LocationStack[LocationStack.Depth-3].StartLine);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 68: // unary -> factor
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
        }
        break;
      case 69: // factor -> OpenRound, exp, CloseRound
{
            CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
        }
        break;
      case 70: // factor -> Ident
{
            CurrentSemanticValue.node = new Ident(ValueStack[ValueStack.Depth-1].val);
            CurrentSemanticValue.node.CheckType();
        }
        break;
      case 71: // factor -> IntNumber
{
            CurrentSemanticValue.node = new Variable("int", ValueStack[ValueStack.Depth-1].val);
        }
        break;
      case 72: // factor -> DoubleNumber
{
            CurrentSemanticValue.node = new Variable("double", ValueStack[ValueStack.Depth-1].val);
        }
        break;
      case 73: // factor -> True
{
            CurrentSemanticValue.node = new Variable("bool", "true");
        }
        break;
      case 74: // factor -> False
{
            CurrentSemanticValue.node = new Variable("bool", "false");
        }
        break;
      case 75: // error_eof -> error, Eof
{
            Console.WriteLine(LocationStack[LocationStack.Depth-2].StartLine + " " + LocationStack[LocationStack.Depth-2].EndLine + " " + LocationStack[LocationStack.Depth-2].StartColumn + " " + LocationStack[LocationStack.Depth-2].EndColumn);
        }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


    public Parser(Scanner scanner) : base(scanner) { }

    public void Print(SyntaxTree node)
    {
        string delim = "";
        node.Print(delim);
    }

    public void PrintSyntaxError(string message, int line = -1) {
        ++Compiler.errors;
        Console.WriteLine(message + " " + line);
    }
}
}
